### ISSUE TITLE
Save member info

### ISSUE THREAD

**Issue by SaharaParker** [SaharaParker/WFHJournal#1]
Be able to save new member info into database.

**Comment by deletosh** [comment]
@SaharaParker I want to confirm, is this what you're working on first?

**Comment by SaharaParker** [comment]
@thedeletosh Yes, I wanted to save the new member info first, but should I do the log in info first instead?

**Comment by deletosh** [comment]
@SaharaParker you don't have to build this yourself, take a look how it's already built into supabase. I will recommend have a table called `profiles` with two columns, `first_name`, `last_name`, `avatar`.

See this: https://supabase.com/docs/guides/auth#user-management
