### ISSUE TITLE
Member login

### ISSUE THREAD

**Issue by SaharaParker** [SaharaParker/WFHJournal#2]
Members should be able to log in with data from supabase.

**Comment by SaharaParker** [comment]
Getting some errors when trying to login. @thedeletosh 
<img width="268" alt="login errors" src="https://user-images.githubusercontent.com/93682682/156008154-ad843479-f1e9-415b-9006-cccac3ae7e29.png">

**Comment by deletosh** [comment]
@SaharaParker as shared, here's. the recording of how we resolved this: https://www.loom.com/share/cf61e84a40344f53ad2330ed4ddfee78

**Comment by deletosh** [comment]
@SaharaParker this is nice to see this overcome 👍🏿
